/***********************************************************************************************************************
 * File Name    : hal_entry.cpp
 * Description  : Contains data structures and functions used in hal_entry.cpp.
 **********************************************************************************************************************/
/***********************************************************************************************************************
* Copyright (c) 2023 - 2026 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
***********************************************************************************************************************/

#include "adc_ep.h"

#if (1 == BSP_MULTICORE_PROJECT) && BSP_TZ_SECURE_BUILD
bsp_ipc_semaphore_handle_t g_core_start_semaphore =
{
    .semaphore_num = 0
};
#endif

volatile bool g_ready_to_read = false;

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used. This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    /* ADC object */
    adc_ep adc;
    fsp_err_t err = FSP_SUCCESS;
    while (true)
    {
        if (APP_CHECK_DATA)
        {
            err = adc.read_process_input_from_RTT();

            /* Handle error */
            if (FSP_SUCCESS != err)
            {
                /* ADC scan start or stop failed, cleanup the ADC initialization */
                adc.deinit_adc_module();
                /* Destructor, to delete the created object */
                adc.~adc_ep();
                APP_ERR_TRAP(err);
            }
        }
        /* Read the ADC output data and status */
        if (true == g_ready_to_read)
        {
            err = adc.adc_read_data();
        }

        /* Handle error */
        if (FSP_SUCCESS != err)
        {
            /* ADC reading failed, cleanup the ADC initialization */
            adc.deinit_adc_module();
            /* Destructor, to delete the created object */
            adc.~adc_ep();
            APP_ERR_TRAP(err);
        }
    }
    /* Wake up 2nd core if this is first core and we are inside a multicore project. */
#if (0 == _RA_CORE) && (1 == BSP_MULTICORE_PROJECT) && !BSP_TZ_NONSECURE_BUILD

#if BSP_TZ_SECURE_BUILD
    /* Take semaphore so 2nd core can clear it */
    R_BSP_IpcSemaphoreTake(&g_core_start_semaphore);
#endif

    R_BSP_SecondaryCoreStart();

#if BSP_TZ_SECURE_BUILD
    /* Wait for 2nd core to start and clear semaphore */
    while(FSP_ERR_IN_USE == R_BSP_IpcSemaphoreTake(&g_core_start_semaphore))
    {
        ;
    }
#endif
#endif

#if (1 == _RA_CORE) && (1 == BSP_MULTICORE_PROJECT) && BSP_TZ_SECURE_BUILD
    /* Signal to 1st core that 2nd core has started */
    R_BSP_IpcSemaphoreGive(&g_core_start_semaphore);
#endif

#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

#if BSP_TZ_SECURE_BUILD

FSP_CPP_HEADER
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build
 * (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
FSP_CPP_FOOTER

#endif
